remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: Thiago Santana's CV
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ptbr.md
  - en.md
